services:
  - type: web
    name: digit-classification-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false   # You will paste this manually in Render dashboard
      - key: SECRET_KEY
        sync: false   # You will set this manually in Render dashboard
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      - key: HF_MODEL_URL
        value: https://huggingface.co/akashi1017/digit-classification-mnist/resolve/main/best_mnist_cnn.keras
      - key: HF_FALLBACK_URL
        value: https://huggingface.co/akashi1017/digit-classification-mnist/resolve/main/best_model.pb
